# Spring Boot configuration
spring:
  datasource:
    url: jdbc:timesten:client:TTC_SERVER=10.9.2.43;TTC_SERVER_DSN=FOHFT;TCP_PORT=53387;
    username: FOHFT
    password: FOHFT
    driverClassName: com.timesten.jdbc.TimesTenDriver
    hikari:
      maximum-pool-size: 4
      auto-commit: false
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.TimesTenDialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

application:
  record-persistence:
    file: /var/caffeine-timesten-snapshot/record-persistence
    ftp:
      host: 10.9.2.43
      user: caffeine
      pwd: caffeine
      working-dir: /ftp/upload